INSERT INTO Family VALUES('awest@gmail.com', 'arnold.westad@gmail.com' , 'father');
INSERT INTO Family VALUES('mbeck@nova.edu', 'scottbeckner@gmail.com', 'father');
INSERT INTO Family VALUES('wsf305@drexel.edu' , 'dan.finelli@yahoo.com' , 'father');
INSERT INTO Family VALUES('jen.westad@gmail.com', 'awest@gmail.com', 'brother');
INSERT INTO Family VALUES( 'jen.westad@gmail.com', 'westadj@sas.upenn.edu' , 'brother');
INSERT INTO Family VALUES( 'mbeck@nova.edu', 'megbeckner@jmu.edu', 'sister');
INSERT INTO Family VALUES( 'mbeck@nova.edu', 'mellbeckner@yahoo.com', 'sister');
INSERT INTO Family VALUES('awest@gmail.com','jen.westad@gmail.com', 'sister');
INSERT INTO Family VALUES('dan.finelli@yahoo.com' , 'wsf305@drexel.edu' , 'son');
INSERT INTO Family VALUES('lizashton@yahoo.com' , 'jashton@seas.upenn.edu', 'son');
INSERT INTO Family VALUES('jashton@seas.upenn.edu', 'lizashton@yahoo.com', 'mother');
INSERT INTO Family VALUES('mbeck@nova.edu', 'susan.beckner@gmail.com', 'mother');
INSERT INTO Family VALUES('scottbeckner@gmail.com','mbeck@nova.edu', 'daughter');
INSERT INTO Family VALUES('hallieballie@hotmail.com' , 'surferdude99@yahoo.co.uk', 'cousin');
INSERT INTO Family VALUES('lyd.jasp@gmail.com' , 'mbeck@nova.edu' , 'cousin');
INSERT INTO Family VALUES('mbeck@nova.edu' , 'lyd.jasp@gmail.com' , 'cousin');
INSERT INTO Family VALUES(  'lyd.jasp@gmail.com' , 'megbeckner@jmu.edu' , 'cousin');
INSERT INTO Family VALUES( 'megbeckner@jmu.edu' , 'lyd.jasp@gmail.com' , 'cousin');
INSERT INTO Family VALUES('natvul@gmail.com' , 'mupton@wharton.upenn.edu' , 'cousin');
