INSERT INTO Friends VALUES('awest@gmail.com', 'jen.westad@gmail.com');
INSERT INTO Friends VALUES('jen.westad@gmail.com', 'awest@gmail.com');
INSERT INTO Friends VALUES('lizashton@yahoo.com', 'jashton@seas.upenn.edu');
INSERT INTO Friends VALUES('jashton@seas.upenn.edu' , 'lizashton@yahoo.com');
INSERT INTO Friends VALUES('awest@gmail.com', 'mbeck@nova.edu');
INSERT INTO Friends VALUES('mbeck@nova.edu', 'awest@gmail.com');
INSERT INTO Friends VALUES('surferdude99@yahoo.co.uk', 'hallieballie@hotmail.com');
INSERT INTO Friends VALUES('hallieballie@hotmail.com' , 'surferdude99@yahoo.co.uk');
INSERT INTO Friends VALUES('hlc209@temple.edu' , 'mellbeckner@gmail.com');
INSERT INTO Friends VALUES('mellbeckner@yahoo.com' , 'hlc209@temple.edu' );
INSERT INTO Friends VALUES('hlc209@temple.edu' , 'luken@temple.edu');
INSERT INTO Friends VALUES('luken@temple.edu' , 'hlc209@temple.edu' );
INSERT INTO Friends VALUES('luken@temple.edu' , 'boser@seas.upenn.edu');
INSERT INTO Friends VALUES('boser@seas.upenn.edu' , 'luken@temple.edu' );
INSERT INTO Friends VALUES('natvul@gmail.com' , 'mupton@wharton.upenn.edu');
INSERT INTO Friends VALUES('mupton@wharton.upenn.edu' , 'natvul@gmail.com');
INSERT INTO Friends VALUES('natvul@gmail.com' , 'jashton@seas.upenn.edu');
INSERT INTO Friends VALUES('jashton@seas.upenn.edu' , 'natvul@gmail.com' );
INSERT INTO Friends VALUES('richterder@sas.upenn.edu' , 'awest@gmail.com');
INSERT INTO Friends VALUES('awest@gmail.com' , 'richterder@sas.upenn.edu');
INSERT INTO Friends VALUES('richterder@sas.upenn.edu' , 'ka.mazejy@yahoo.com' );
INSERT INTO Friends VALUES('ka.mazejy@yahoo.com' , 'richterder@sas.upenn.edu');
INSERT INTO Friends VALUES('wsf305@drexel.edu' , 'richterder@sas.upenn.edu');
INSERT INTO Friends VALUES( 'richterder@sas.upenn.edu', 'wsf305@drexel.edu' );
INSERT INTO Friends VALUES( 'richterder@sas.upenn.edu' , 'hlc209@temple.edu' );
INSERT INTO Friends VALUES( 'hlc209@temple.edu' , 'richterder@sas.upenn.edu');
INSERT INTO Friends VALUES( 'lyd.jasp@gmail.com' , 'natvul@gmail.com');
INSERT INTO Friends VALUES(  'mbeck@nova.edu' , 'lyd.jasp@gmail.com');
INSERT INTO Friends VALUES(  'lyd.jasp@gmail.com' , 'mbeck@nova.edu');
INSERT INTO Friends VALUES(  'megbeckner@jmu.edu' , 'lyd.jasp@gmail.com');
INSERT INTO Friends VALUES(  'lyd.jasp@gmail.com' , 'megbeckner@jmu.edu');
INSERT INTO Friends VALUES( 'natvul@gmail.com' , 'lyd.jasp@gmail.com');