INSERT INTO Person VALUES('awest@gmail.com', 'Ashton Westad', 'male', 'relationship', 1989);
INSERT INTO Person VALUES('jen.westad@gmail.com', 'Jenny Westad', 'female', 'single', 1992);
INSERT INTO Person VALUES('lizashton@yahoo.com', 'Elizabeth Ashton' , 'female', 'married', 1968);
INSERT INTO Person VALUES('jashton@seas.upenn.edu', 'John Ashton', 'male', 'single', 1990);
INSERT INTO Person VALUES('mbeck@nova.edu', 'Meredith Beckner', 'female', 'single', 1989);
INSERT INTO Person VALUES('megbeckner@jmu.edu', 'Meghan Beckner', 'female', 'single', 1990);
INSERT INTO Person VALUES('mellbeckner@yahoo.com', 'Melanie Beckner', 'female', 'single', 1997);
INSERT INTO Person VALUES('susan.beckner@gmail.com', 'Susan Beckner', 'female', 'married', 1961);
INSERT INTO Person VALUES('scottbeckner@gmail.com', 'Scott Beckner', 'male', 'married', 1960);
INSERT INTO Person VALUES('hallieballie@hotmail.com', 'Hallie Bail', 'female', 'single', 1997);
INSERT INTO Person VALUES('surferdude99@yahoo.co.uk', 'Ryan Mckaskall', 'male', 'single', 1999);
INSERT INTO Person VALUES('boser@seas.upenn.edu' , 'Richard Boser' , 'male' , 'single' , 1991);
INSERT INTO Person VALUES( 'hlc209@temple.edu' , 'Hannah Cochran' , 'female' , 'relationship' , 1994);
INSERT INTO Person VALUES( 'wsf305@drexel.edu' , 'West Finelli' , 'male' , 'single' , 1983);
INSERT INTO Person VALUES('dan.finelli@yahoo.com' , 'Daniel Finelli' , 'male' , 'divorced' , 1954); 
INSERT INTO Person VALUES( 'lyd.jasp@gmail.com' , 'Lydia Jasper' , 'female' , 'single' , 1991);
INSERT INTO Person VALUES('ka.mazejy@yahoo.com' , 'Kristin Mazejy' , 'female' , 'single' , 1987);
INSERT INTO Person VALUES('luken@templ.edu' , 'Luke Newton' , 'male' , 'single' , 1995);
INSERT INTO Person VALUES('richterder@sas.upenn.edu' , 'Derek Richter' , 'male' , 'single' , 1988);
INSERT INTO Person VALUES('mupton@wharton.upenn.edu' , 'Marcus Upton' , 'male' , 'relationship' , 1990);
INSERT INTO Person VALUES( 'natvul@gmail.com' , 'Natalie Vulcan' , 'female' , 'relationship' , 1995);
INSERT INTO Person VALUES('westadj@sas.upenn.edu' , ' Josh Westad' , 'male' , 'single' , 1987);
INSERT INTO Person VALUES('arnold.westad@gmail.com' , 'Arnold Westad' , 'male' , 'married' , 1958);